"""added checked field in order table

Revision ID: 5786e3e3ba1f
Revises: 7e6ef012518e
Create Date: 2024-03-21 15:02:02.880514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5786e3e3ba1f'
down_revision = '7e6ef012518e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('checked')

    # ### end Alembic commands ###
