"""changed type to radio button

Revision ID: 916a2948f738
Revises: 5786e3e3ba1f
Create Date: 2024-03-23 10:24:12.674257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916a2948f738'
down_revision = '5786e3e3ba1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)

    # ### end Alembic commands ###
